##########
# collectionbuilder-sa
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-sa
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: http://upslis.info
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /SLISat60
# location of code, the full url to your github repository
source-code: https://github.com/pvperez1/slis60_draft

##########
# SITE SETTINGS
#
# title of site appears in banner
title: UP SLIS @ 60
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Challenging Traditions. Embracing Innovations
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "This Digital Exhibit celebrates the milestones and achievement of the UP School of Library and Information Studies"
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: upslis; library and information science; 60th anniversary
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: pvperez1
# Organization branding
organization-name: "UP School of Library and Information Studies"
organization-link: http://upslis.info
organization-logo-banner: http://upslis.info/images/logolong.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

##########
# COLLECTION SETTINGS
#
# provide location of the digital objects folder,
# If using local folder, dir name with proceeding slash. If using external web location, provide full URL
objects: /objects 
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: demo-metadata
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  


##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# if present, used to add analytics during "production" build only
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
